repos:
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        language_version: python3
        args: [-l 100]
  - repo: https://github.com/sqlalchemyorg/zimports
    rev: 0.1.3
    hooks:
      - id: zimports
        exclude: ^migrations/
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear==19.3.0]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
  - repo: git://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
    - id: shell-lint
      args: [--format=json]
