name: publish-to-quay
on:
  push:
    branches:
      - master
env:
  REPOSITORY: quay.io/refgenomics/covid19
  TAG: latest

jobs:
  publish-to-quay:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Show the secret
        run: |
          echo "Super secret value: ${{ secrets.SUPER_SECRET_VALUE }}"
      - name: Login to Quay
        shell: bash
        run: echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} quay.io --password-stdin

      - name: Docker build
        shell: bash
        run: |
          export DOCKER_BUILDKIT=1
          docker build \
            -t ${REPOSITORY}:${TAG} \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ${REPOSITORY}:${TAG} .

      - name: Push to quay
        shell: bash
        run: |
          docker push ${REPOSITORY}:${TAG}
