name: publish-to-quay
on:
  push:
    branches:
      - master
env:
  IMAGE_BASE: quay.io/refgenomics/covid19

jobs:
  publish-to-quay:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          lfs: true

      - name: Login to Quay
        shell: bash
        run: echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} quay.io --password-stdin

      - name: Set env
        run: |
          echo "--- RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "--- building & pushing ${IMAGE_BASE}:${{env.RELEASE_VERSION}}"

      - name: Docker build
        shell: bash
        run: |
          export DOCKER_BUILDKIT=1
          docker build \
            -t ${IMAGE_BASE}:${{env.RELEASE_VERSION}} \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ${IMAGE_BASE}:${{env.RELEASE_VERSION}} .

      - name: Push to quay
        shell: bash
        run: |
          docker push ${IMAGE_BASE}:${{env.RELEASE_VERSION}}
