name: publish-to-quay
on:
  push:
    branches:
      - master
env:
  REPOSITORY: quay.io/refgenomics/covid19

jobs:
  publish-to-quay:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          lfs: true

      - name: Show the secret
        run: |
          echo "Super secret value: ${{ secrets.SUPER_SECRET_VALUE }}"

      - name: Login to Quay
        shell: bash
        run: echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} quay.io --password-stdin

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Print Tag
        shell: bash
        run: echo "--- building & pushing ${REPOSITORY}:${{env.RELEASE_VERSION}}"

      - name: Docker build
        shell: bash
        run: |
          export DOCKER_BUILDKIT=1
          docker build \
            -t ${REPOSITORY}:${{env.RELEASE_VERSION}} \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ${REPOSITORY}:${{env.RELEASE_VERSION}} .

      - name: Push to quay
        shell: bash
        run: |
          docker push ${REPOSITORY}:${{env.RELEASE_VERSION}}
